//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALM_Upgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Project
    {
        public Customer_Project()
        {
            this.Project_Email = new HashSet<Project_Email>();
            this.ProjectList = new HashSet<ProjectList>();
        }
    
        public int id { get; set; }
        public string customer_name { get; set; }
        public string customer_url { get; set; }
        public bool deactivation { get; set; }
        public bool undo_checkouts { get; set; }
        public bool copy_file { get; set; }
        public bool copy_db { get; set; }
        public bool change_file { get; set; }
        public bool restore_project { get; set; }
        public bool verify_project { get; set; }
        public bool upgrade_project { get; set; }
        public bool verification { get; set; }
        public bool release { get; set; }
        public Nullable<System.Guid> customerId { get; set; }
        public bool initialNotification { get; set; }
        public bool finalNotification { get; set; }
        public string service_id { get; set; }
        public bool upgrade_type { get; set; }
        public string upgrade_version { get; set; }
        public bool dry_run { get; set; }
    
        public virtual ICollection<Project_Email> Project_Email { get; set; }
        public virtual ICollection<ProjectList> ProjectList { get; set; }
    }
}
