//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALM_Upgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Project
    {
        public Customer_Project()
        {
            this.Project_Email = new HashSet<Project_Email>();
            this.ProjectList = new HashSet<ProjectList>();
        }
    
        public int id { get; set; }
        public string customer_name { get; set; }
        public string customer_url { get; set; }
        public bool deactivation { get; set; }
        public bool undo_checkouts { get; set; }
        public bool copy_file { get; set; }
        public bool copy_db { get; set; }
        public bool change_file { get; set; }
        public bool restore_project { get; set; }
        public bool verify_project { get; set; }
        public bool upgrade_project { get; set; }
        public bool verification { get; set; }
        public bool release { get; set; }
        public Nullable<System.Guid> customerId { get; set; }
        public bool initialNotification { get; set; }
        public bool finalNotification { get; set; }
        public string service_id { get; set; }
    
        public virtual ICollection<Project_Email> Project_Email { get; set; }
        public virtual ICollection<ProjectList> ProjectList { get; set; }
    }
}
