//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALM_Upgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectList
    {
        public int id { get; set; }
        public int customer_project_id { get; set; }
        public string project_name { get; set; }
        public string domain_name { get; set; }
        public bool finished { get; set; }
    
        public virtual Customer_Project Customer_Project { get; set; }
    }
}
