//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALM_Upgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectList
    {
        public int id { get; set; }
        public int customer_project_id { get; set; }
        public string project_name { get; set; }
        public string domain_name { get; set; }
        public bool finished { get; set; }
    
        public virtual Customer_Project Customer_Project { get; set; }
    }
}
