//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALM_Upgrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersPermissions
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int PermissionID { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual Users Users { get; set; }
    }
}
